### ISSUE TITLE
work in progress for Linux version ?

### ISSUE THREAD

**Issue by patrix67** [Ombrelin/pandoc-gui#21]
It would be interesting to provide the port to Linux. Is this planned for soon ? Thank you for your response.

**Comment by Ombrelin** [comment]
Hello ! 
The issue is that I'm not experienced in publishing client apps for Linux, what should I do ? A flatpak ? A .deb ?
If you have any insight on the subject, I'll be happy to try and make it happen.

**Comment by patrix67** [comment]
Thank you for your answer. I'm not experienced too. Flatpak or .deb would be good (I'm under Ubuntu).
Sincerely,

**Comment by Ombrelin** [comment]
Ok I'll look into that and try to achieve something !

**Comment by Ombrelin** [comment]
I've myself  adopted linux (Ubuntu) as my main desktop operating system and that's why I'm working actively on publishing the app as a flatpak, I'll keep you posted on the subject

**Comment by Ombrelin** [comment]
All things considered, it won't be a flatpak, but rather a deb package since the flatpak sandboxing makes it difficult to invoke pandoc CLI from the app

**Comment by Ombrelin** [comment]
debian package for the linux version is available !! Closing this then
