### ISSUE TITLE
Provide a packaging for MacOS

### ISSUE THREAD

**Issue by Dcrizz** [Ombrelin/pandoc-gui#24]
Hello

Firstly, thanks for taking the time to make this! I am particularly knowledgeable about computers so this looks like it will be a great help in converting my word docs to markdown for Obsidian. 

I am having trouble getting it to run on my Mac when I type the run command into the terminal  it comes up with this

```
fatal: destination path 'pandoc-gui' already exists and is not an empty directory.
cd: no such file or directory: pandoc-gui/PandocGui
Couldn't find a project to run. Ensure a project exists in /Users/dockray, or pass the path to the project using --project. 
```

I already have installed the pandoc and Tex packages. Is there something I am missing or doing wrong?

Thanks for any help you can offer!!

**Comment by Ombrelin** [comment]
Hi ! First, sorry for the fact that I can't provide a macOS install package, since I don't own a mac :'(
Regarding your problem, it's my fault, I've not kept the instruction on the readme up to data with the restructuring of the repository. Your should rather type : 
```bash
cd pandoc-gui/src/PandocGui
dotnet run
```
Just fixed it on the readme !

**Comment by Dcrizz** [comment]
Hello

Thanks for getting back to me! No need to apologise, thank you for making this anyway as it will be a big help to me! Works like a dream now, so thanks very much again!!

**Comment by Ombrelin** [comment]
MacOS packing mentioned in #4, closing this one
